<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<!-- dotnet tool packaging -->
	<PropertyGroup>
	<PackAsTool>true</PackAsTool>
	<ToolCommandName>xycmd</ToolCommandName>
	<PackageId>xyCmdCheatSheet</PackageId>
	<PackageVersion>1.0.2</PackageVersion>
	<Authors>ThrashingLaggard</Authors>
	<Description>CLI-Tool to show (custom WIP) commands in the cli.
  usage:
                 cmd   -   all commands
	cmd [git/dotnet/...]	-   show commands of a specific category
	cmd --list   -   show only the categories
	</Description>
	<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>
	<GenerateDocumentationFile>True</GenerateDocumentationFile>
	<PackageReadmeFile>README.md</PackageReadmeFile>
	</PropertyGroup>
	<ItemGroup>
	  <None Include="..\README.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>
	<ItemGroup>
	  <Folder Include="Infos\" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="xyToolz" Version="1.2.1" />
	</ItemGroup>

</Project>
